require('Plugins.cmp')
require('Plugins.lsp')
require('Plugins.nvim-tree')
require('Plugins.lualine')
require('Plugins.tokyonight')
require('Plugins.blankline')
require('Plugins.bufferline')
--snip
require("luasnip.loaders.from_vscode").lazy_load()
--autocomments
require('Comment').setup()
--nvim-treesitter-setup↴
require'nvim-treesitter.configs'.setup{highlight={enable=true}}
