local r = require
r('Plugins.cmp')
r('Plugins.lsp')
r('Plugins.nvim-tree')
r('Plugins.lualine')
r('Plugins.tokyonight')
r('Plugins.blankline')
r('Plugins.bufferline')
r('Plugins.mason')
r('Plugins.comment')
r('Plugins.treesitter')
r('Plugins.snippets')
